file:
    test/mergetwomoredocument/oneforall_output:
        csv_delimiter: ','
        data:
            domain: subdomain
            source: source
        type: csv
    test/mergetwomoredocument/subfinder_output:
        csv_delimiter: ','
        data:
            domain: host
            source: source
        type: json
output:
    filename: out.data
    formatistext: false
    outputfield: ""
    structdefine: struct { Name   string `select:"domain"`;Source string `select:"source"`}
used: true
