file:
    test/mergetwomoredocument/oneforall_output:
        csv_delimiter: ','
        data:
            domain: host
            source: source
        type: csv
    test/mergetwomoredocument/subfinder_output:
        csv_delimiter: ','
        data:
          domain: subdomain
          source: source
        type: json
used: true
