name: pull on docker

on:
  push:
    branches: [ 'Skyworship' ]

env:
  # if you are using Dockerhub
  # please named as your dockerhub username
  # like DOCKER_REGISTER: wujunyi792
  # if you are using Aliyun Registry
  # please named as your Aliyun Registry username
  #
  # Alternative: upload to esoncloud docker registry
  #

  # your Image name
  CONTAINER: esonhugh/merger

  # OTHER Variable of your project
  # secret: you need to defined in secrets
  # username is  Docker Register username
  #          username: ${{ secrets.DOCKER_USERNAME }}
  # password is pair with username
  #          password: ${{ secrets.DOCKER_PASSWORD }}
  # SSH_PUSH_PRIVATE_KEY is your git ssh private key. Push it on the git repo. Must have "Write" prem.
  #          SSH_PRIVATE_KEY: ${{ secrets.SSH_PUSH_PRIVATE_KEY }}

jobs:
  build-base:
    name: Build Base
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CONTAINER }}
          tags: |
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
